' Preview: Alt + D  (z. B. in VS Code)

@startuml ER Diagramm: Firma

hide circle
skinparam linetype ortho

entity "Firma" {

id: integer <<generated>>--
version: integer
name: text
gruendungsjahr: integer
branche: text
mitarbeiteranzahl: integer
umsatz: decimal(12,2)
homepage: text
erzeugt: timestamp
aktualisiert: timestamp
}

entity "Geschaeftsfuehrer" {

id: integer <<generated>>--
name: text
email: text
telefon: text
firma_id: integer <<FK>>
erzeugt: timestamp
aktualisiert: timestamp
}

entity "Standort" {

id: integer <<generated>>--
adresse: text
plz: text
ort: text
land: text
firma_id: integer <<FK>>
erzeugt: timestamp
aktualisiert: timestamp
}

entity "Firma_File" {

id: integer <<generated>>--
data: bytea
filename: text
mimetype: text
firma_id: integer <<FK>>
}

' Beziehungen
Firma -- Geschaeftsfuehrer : "1 : 1"
Firma --o{ Standort : "1 : n"
Firma --|| Firma_File : "1 : 1"


@enduml
